const theme = {
    colors: {
      primary: "#007bfe",
     test:"#6d6e75",
     secondary: "#fdfdfd",
     grey:"#dedede",
     backgrounGrey:"#f3f3f3",
     black:"#0c0d19",
     lightwhite:"#F5F5F5",
     brightblue: "#007BFF",
     vividblue: "#0494FA",
     aliceBlue: "#F1F4FF",
     pastelBlue: "#94C8FF",
     royalBlue: "#435EBE",
     lightgray: "#BDBECC",
     platinumlightgray: "#EDEDED",
     darkgray: "#252525",
     silvergray: "#AEAEAE",
     chorcoalgray: "#313131",
     lavendargray: "#D4D7EA",
     silverGray: "#B1B2B5",
     dimGray: "#696969",
     charcoalGray: "#272727",
     pureblack: "#000000",
     blueishblack: "#0C0D19",
     jetBlack: "#2F2F2F",
     white: "#FFFFFF",
     emaraldgreen: "#20A100",
     goldenyellow:"#D4B200",
     crimsonRed: "#FB4F4F",
     logoutButtonColor: "#FF2E00",
     
    },
    fonts: {
      body: "'DM Sans', sans-serif",
      heading: "'Montserrat', sans-serif",
      monospace: "'Source Sans 3', monospace",
      accent: "'Nunito', sans-serif",
      display: "'Outfit', sans-serif",
      body2: "'Poppins', sans-serif",
    },
    breakpoints: {
      mobile: "480px",
      tablet: "768px",
      desktop: "1024px",
    },
    spacing: (factor) => `${factor * 8}px`,
  };
  
  export default theme;
  